In [243]:
#Sheet 4 Exercise 14 Power Method

In [244]:
import numpy as np
from scipy import linalg

In [245]:
n = int(input('Input Matrix size n:'))
h = np.array([4,-1,-2])
if(n>=3):
    r = np.concatenate((h,np.zeros(n-h.size)),axis=None)
else:
    if(n == 1):
        r = np.array([4])
    else:
        r = np.array([4,-1])
    

In [246]:
t = linalg.toeplitz(r,r)
print('Toeplitz Matrix : \n', t)

Toeplitz Matrix : 
 [[ 4. -1. -2.  0.  0.  0.  0.  0.  0.]
 [-1.  4. -1. -2.  0.  0.  0.  0.  0.]
 [-2. -1.  4. -1. -2.  0.  0.  0.  0.]
 [ 0. -2. -1.  4. -1. -2.  0.  0.  0.]
 [ 0.  0. -2. -1.  4. -1. -2.  0.  0.]
 [ 0.  0.  0. -2. -1.  4. -1. -2.  0.]
 [ 0.  0.  0.  0. -2. -1.  4. -1. -2.]
 [ 0.  0.  0.  0.  0. -2. -1.  4. -1.]
 [ 0.  0.  0.  0.  0.  0. -2. -1.  4.]]


In [247]:
def eigenVal(a):
    n = len(a)
    x0 = np.ones(n)
    x = np.divide(np.matmul(a,x0),np.linalg.norm(x0))
    while(np.linalg.norm(x-x0) > 10E-12):
        x0 = np.copy(x)
        x = np.divide(np.matmul(a,x0),np.linalg.norm(x0))
    return np.linalg.norm(x)

In [248]:
print('Using definition :')
print('Largest absolute Eigen Value of Toeplitz Matrix A of size %d = %s '%(n,eigenVal(t)))
la, v = np.linalg.eig(t)
print('Using numpy and scipy :')
print('Largest absolute Eigen Value of Toeplitz Matrix A of size %d = %s '%(n,la.max()))

Using definition :
Largest absolute Eigen Value of Toeplitz Matrix A of size 9 = 7.515316029450962 
Using numpy and scipy :
Largest absolute Eigen Value of Toeplitz Matrix A of size 9 = 7.515316029450963 
